const productss = [
  {
    _id: "651edb9fb9bf0834487f33fe",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "৪৪তম বিসিএস প্রিলিমিনারি",
    description:
      "এই প্রোডাক্টটি প্রাথমিক পরীক্ষার জন্য একটি সম্পূর্ণ অধ্যয়ন উপাদান প্রদান করে। এটি বিসিএস প্রিলিমিনারি পরীক্ষার জন্য সমস্ত প্রস্তুতি এবং অনুশাসন উন্নত করতে সাহায্য করবে। এই প্রোডাক্টটি বিভিন্ন বিষয়ের নির্দেশনা, ব্যাক্তিগত স্টাডি প্ল্যান, এবং সোল্যুশন সহিত সম্পূর্ণ হাতেকলমে তৈরি করা হয়েছে। এই প্রোডাক্টটি প্রাথমিক পরীক্ষার জন্য আপনার স্বপ্নপুরী পেশায় এক স্টেপ আগে যেতে সাহায্য করবে।",
    regularPrice: 50,
    newest: true,
    offerPrice: 45,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
    status: "in-stock",
  },
  {
    _id: "651edb9fb9bf0834487f33ff",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "৫০তম বিসিএস প্রিলিমিনারি",
    description:
      "এই সম্পূর্ণ অধ্যয়ন উপাদানটি আপনার ৫০তম বিসিএস প্রিলিমিনারি পরীক্ষার জন্য সকল প্রস্তুতি এবং সঠিক দিকে প্রেরণা প্রদান করবে। এটি বিভিন্ন বিষয়ের আচরণ প্রশ্নের সাথে সম্পূর্ণ উত্তর এবং সাহায্যকারী প্রশ্নোত্তর, উপস্থাপনা, এবং অধ্যয়ন সূচিগুলির সাথে আসে। এই প্রোডাক্টটি পরীক্ষার জন্য সঠিক পথে আপনাকে নেতৃত্ব দেবে এবং আপনার প্রস্তুতি নিরাপদ করতে সাহায্য করবে।",
    regularPrice: 60,
    newest: true,
    offerPrice: 55,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
    status: "in-stock",
  },
  {
    _id: "651edb9fb9bf0834487f3400",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "৫৩তম বিসিএস প্রিলিমিনারি",
    description:
      "এই প্রোডাক্টটি আপনাকে ৫৩তম বিসিএস প্রিলিমিনারি পরীক্ষার জন্য সম্পূর্ণ প্রস্তুত করতে সাহায্য করবে। এটি সম্পূর্ণ অধ্যয়ন উপাদান সহিত, বিভিন্ন বিষয়ের জন্য পরীক্ষার স্থানান্তরণ এবং সময় ব্যবস্থাপনা পর্যাপ্তভাবে প্রদান করে। এই প্রোডাক্টটি আপনার প্রিলিমিনারি পরীক্ষার জন্য নিরাপদ প্রস্তুতি নিশ্চিত করতে সাহায্য করবে।",
    regularPrice: 40,
    newest: true,
    offerPrice: 35,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
    status: "in-stock",
  },
  {
    _id: "651edb9fb9bf0834487f3401",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "৪৯তম বিসিএস প্রিলিমিনারি",
    description:
      "এই প্রোডাক্টটি আপনাকে ৪৯তম বিসিএস প্রিলিমিনারি পরীক্ষার জন্য সম্পূর্ণ অধ্যয়ন উপাদান প্রদান করবে। এটি বিভিন্ন বিষয়ের জন্য সঠিক দিকে প্রেরণা প্রদান করবে এবং আপনাকে পরীক্ষার সময় প্রস্তুত করতে সাহায্য করবে।",
    regularPrice: 70,
    newest: true,
    offerPrice: 65,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
    status: "in-stock",
  },
  {
    _id: "651edb9fb9bf0834487f3402",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "৭০তম বিসিএস প্রিলিমিনারি",
    description:
      "এই সম্পূর্ণ অধ্যয়ন উপাদানটি আপনার ৭০তম বিসিএস প্রিলিমিনারি পরীক্ষার জন্য এবং সফলভাবে প্রস্তুত হতে সাহায্য করবে। এটি সম্পূর্ণ অধ্যয়ন উপাদান, প্রশ্নের সাথে সঠিক উত্তর, এবং পরীক্ষার দিকে সঠিক দিকে প্রেরণা প্রদান করে।",
    regularPrice: 55,
    newest: true,
    offerPrice: 50,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
    status: "in-stock",
  },
  {
    _id: "651edb9fb9bf0834487f3403",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "২০তম বিসিএস প্রিলিমিনারি",
    description:
      "এই প্রোডাক্টটি আপনাকে ২০তম বিসিএস প্রিলিমিনারি পরীক্ষার জন্য সম্পূর্ণ অধ্যয়ন উপাদান প্রদান করবে। এটি বিভিন্ন বিষয়ের অধ্যয়ন সূচি, উত্তর, এবং পরীক্ষার সঠিক দিকে প্রেরণা প্রদান করে।",
    regularPrice: 45,
    newest: true,
    offerPrice: 40,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
    status: "in-stock",
  },
  {
    _id: "651edb9fb9bf0834487f3404",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "৪৪তম বিসিএস প্রিলিমিনারি",
    description:
      "এই প্রোডাক্টটি প্রাথমিক বিসিএস প্রিলিমিনারি পরীক্ষার জন্য সম্পূর্ণ অধ্যয়ন উপাদান প্রদান করে। এটি সম্পূর্ণ অধ্যয়ন উপাদান, উত্তর, এবং অধ্যয়ন সূচি সহিত প্রস্তুত করা হয়েছে।",
    regularPrice: 30,
    newest: true,
    offerPrice: 25,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
    status: "in-stock",
  },
  {
    _id: "651edb9fb9bf0834487f3405",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "৬২তম বিসিএস প্রিলিমিনারি",
    description:
      "এই প্রোডাক্টটি আপনাকে ৬২তম বিসিএস প্রিলিমিনারি পরীক্ষার জন্য সম্পূর্ণ অধ্যয়ন উপাদান প্রদান করবে এবং আপনার প্রস্তুতি সঠিকভাবে সাথে নেতৃত্ব দেবে।",
    regularPrice: 80,
    newest: true,
    offerPrice: 75,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
    status: "in-stock",
  },
  {
    _id: "651edb9fb9bf0834487f3406",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "৩২",
    description:
      "এই প্রোডাক্টটি আপনাকে ৩২তম বিসিএস প্রিলিমিনারি পরীক্ষার জন্য সম্পূর্ণ অধ্যয়ন উপাদান সহিত সঠিক দিকে প্রেরণা প্রদান করবে।",
    regularPrice: 35,
    offerPrice: 30,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
  },
  {
    _id: "651edb9fb9bf0834487f3407",
    image: "https://i.ibb.co/hKqf0CR/book1.png",
    imageUrls: [
      "https://i.ibb.co/hKqf0CR/book1.png",
      "https://i.ibb.co/hKqf0CR/book1.png",
    ],
    title: "৫৫",
    description:
      "এই সম্পূর্ণ অধ্যয়ন উপাদানটি আপনার ৫৫তম বিসিএস প্রিলিমিনারি পরীক্ষার জন্য এবং সফলভাবে প্রস্তুত হতে সাহায্য করবে। এটি বিভিন্ন বিষয়ের জন্য সঠিক দিকে প্রেরণা প্রদান করে এবং আপনাকে পরীক্ষার দিকে সঠিক দিকে প্রেরণা দেবে।",
    regularPrice: 65,
    newest: false,
    offerPrice: 60,
    discountPrice: 10,
    offerPercentage: 10,
    stock: 10,
    status: "in-stock",
  },
];
export { productss };
